######################################################################
# Automatically generated by qmake (2.01a) s�b ago 30 19:10:50 2014
######################################################################

TEMPLATE = lib
TARGET_DIR = lib
OBJECTS_DIR = build
MOC_DIR = build

DEPENDPATH += . include src

INCLUDEPATH += . include src

HEADERS += \
    include/qsnmpmanager.h \
    include/qsnmpexception.h \
    include/qsnmpobject.h \
    include/qsnmpcore.h \
    include/qsnmpdata.h \
    include/qsnmpoid.h \
    include/qsnmpostream.h \
    include/qmibtree.h \
    include/qtnetsnmp_global.h \
    include/qsnmpglobal.h \
    include/qsnmptypes.h

SOURCES += \
    src/qsnmpmanager.cpp \
    src/qsnmpobject.cpp \
    src/qsnmpcore.cpp \
    src/qsnmpoid.cpp \
    src/qsnmpdata.cpp \
    src/qsnmpostream.cpp \
    src/qmibtree.cpp

LIBS += -lnetsnmp

DEFINES += QTNETSNMP_LIBRARY

unix {
    target.path = /usr/lib
    headers.path = /usr/include/QtNetSNMP
    headers.files = include/*
    documentation.path = /usr/share
    documentation.commands = doxygen
    documentation.files = doc

    INSTALLS += target headers documentation
}

OTHER_FILES += \
    AUTHOR \
    LICENSE \
    README
