######################################################################
# Automatically generated by qmake (2.01a) s�b ago 30 19:10:50 2014
######################################################################

TEMPLATE = lib

# Directories

OTHER_FILES += \
    AUTHOR \
    LICENSE \
    README

HEADERS += \
    include/qsnmpmanager.h

SOURCES += \
    src/qsnmpmanager.cpp
